Eleve:
    type: entity
    table: eleve
    indexes:
        fk_eleve_entreprise1_idx:
            columns:
                - entreprise_identreprise
    id:
        ideleve:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        prenom:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    lifecycleCallbacks: {  }
<<<<<<< HEAD
    oneToMany:
        formation:
            targetEntity: formation
            mappedBy: eleve
        participation:
            targetEntity: participation
            mappedBy: eleve
=======
    manyToOne:
        entreprise:
            targetEntity: entreprise
            inversedBy: eleve
            joinColumn:
                identreprise:
                    referencedColumnName: entreprise_identreprise
>>>>>>> 1600484b8fe13afe8c7377aa7d45b7583b759e57
