Entreprise:
    type: entity
    table: entreprise
    id:
        identreprise:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: identreprise
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    lifecycleCallbacks: {  }
    oneToMany:
        eleve:
            targetEntity: eleve
            mappedBy: entreprise