Formation:
    type: entity
    table: formation
    indexes:
        fk_formation_professeur1_idx:
            columns:
                - professeur_idprofesseur
    id:
        idformation:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idFormation
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        categorie:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
    lifecycleCallbacks: {  }
    oneToMany:
        session:
            targetEntity: session
            mappedBy: formation
    manyToOne:
        eleve:
            targetEntity: eleve
            inversedBy: formation
            joinColumns:
                eleve_ideleve:
                    referencedColumnName: ideleve
        professeur:
            targetEntity: professeur
            inversedBy: formation
            joinColumns:
                professeur_idprofesseur:
                    referencedColumnName: idprofesseur

