Participation:
    type: entity
    table: participation
    indexes:
        fk_participation_session1_idx:
            columns:
                - session_idsession
        fk_participation_eleve1_idx:
            columns:
                - eleve_ideleve
    id:
        idparticipation:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        note:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    lifecycleCallbacks: {  }
    manyToOne:
        eleve:
            targetEntity: eleve
            inversedBy: participation
            joinColumns:
                eleve_ideleve:
                    referencedColumnName: ideleve
        session:
            targetEntity: session
            inversedBy: participation
            joinColumns:
                session_idsession:
                    referencedColumnName: idsession
