Session:
    type: entity
    table: session
    indexes:
        fk_session_professeur1_idx:
            columns:
                - professeur_idprofesseur
        fk_session_salle1_idx:
            columns:
                - salle_idsalle
        fk_session_formation1_idx:
            columns:
                - formation_idFormation
    id:
        idsession:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dateDebut:
            type: datetime
            nullable: true
            column: date_debut
        dateFin:
            type: datetime
            nullable: true
            column: date_fin
    lifecycleCallbacks: {  }
    manyToOne:
        salle:
            targetEntity: salle
            inversedBy: session
            joinColumn:
                salle_idsalle:
                    referencedColumnName: idsalle
        professeur:
            targetEntity: professeur
            inversedBy: session
            joinColumn:
                professeur_idprofesseur:
                    referencedColumnName: idprofesseur
    oneToMany:
        participation:
            targetEntity: participation
            mappedBy: session
