Session:
    type: entity
    table: session
    indexes:
        fk_session_professeur1_idx:
            columns:
                - professeur_idprofesseur
        fk_session_salle1_idx:
            columns:
                - salle_idsalle
        fk_session_formation1_idx:
            columns:
                - formation_idFormation
    id:
        idsession:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dateDebut:
            type: datetime
            nullable: true
            column: date_debut
        dateFin:
            type: datetime
            nullable: true
            column: date_fin
    manyToOne:
        formationformation:
            targetEntity: Formation
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                formation_idFormation:
                    referencedColumnName: idFormation
            orphanRemoval: false
        professeurprofesseur:
            targetEntity: Professeur
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                professeur_idprofesseur:
                    referencedColumnName: idprofesseur
            orphanRemoval: false
        sallesalle:
            targetEntity: Salle
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                salle_idsalle:
                    referencedColumnName: idsalle
            orphanRemoval: false
    manyToMany:
        eleveeleve:
            targetEntity: Eleve
            cascade: {  }
            fetch: LAZY
            mappedBy: sessionsession
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
