<?php



/**
 * EleveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EleveRepository extends Doctrine\ORM\EntityRepository
{
    public function getAllEleveOrderByEntreprise(){
        $qb = $this->_em->createQueryBuilder();

        return $qb->select('e')
            ->from('Eleve', 'e')
            ->orderBy('e.entreprise', 'ASC')->getQuery()->getResult();
    }

}
