<?php



/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends Doctrine\ORM\EntityRepository
{
    public function getSessionByProfesseur($idProfesseur) {
        
        return $this->_em->createQuery('SELECT s FROM Session s WHERE s.professeur = ' . $idProfesseur)->getResult();

    }
}
